id: I722D1507
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T22:12:19+00:00'
last_modified: '2022-06-08T17:28:26.516238+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN4963
  title: ཡིད་བཞིན་རིན་པོ་ཆེའི་མཛོད་རྩ་འགྲེལ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    A670:
      image_group_id: I3CN4965
      title: ''
      total_pages: 518
      order: 1
      base_file: A670.txt
    98F8:
      image_group_id: I3CN4966
      title: ''
      total_pages: 966
      order: 2
      base_file: 98F8.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
