id: P010780
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-20 10:24:12.130938
source_metadata:
  id: bdr:W3CN4963
  title: ཡིད་བཞིན་རིན་པོ་ཆེའི་མཛོད་རྩ་འགྲེལ།
  author: ''
  volumes:
    39f2c71938c74674aa12334eef5edce7:
      image_group_id: I3CN4965
      title: ''
      volume_number: 1
      total_pages: 518
      base_file: v001.txt
    a099ab064c7c444bb71316a62e654618:
      image_group_id: I3CN4966
      title: ''
      volume_number: 2
      total_pages: 966
      base_file: v002.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
